#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/tobby?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#    username: root
#    password: 12341234
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
